cmake_minimum_required(VERSION 3.25)
if(NOT DEFINED DESTINY_ROOT OR NOT DEFINED DESTINY_OUTPUT)
    message(FATAL_ERROR "Inventory requires DESTINY_ROOT and DESTINY_OUTPUT")
endif()
get_filename_component(DESTINY_PROJECT_ROOT "${DESTINY_ROOT}" ABSOLUTE)
set(DESTINY_SOURCE_ROOT "${DESTINY_PROJECT_ROOT}/source")
include("${CMAKE_CURRENT_LIST_DIR}/../DestinyRegistry.cmake")
destiny_collect_modules()
destiny_write_inventory("${DESTINY_OUTPUT}")
