cmake_minimum_required(VERSION 3.25)
foreach(name DESTINY_MODULE DESTINY_FACTS DESTINY_OUTPUT)
    if(NOT DEFINED ${name})
        message(FATAL_ERROR "Header preview requires ${name}")
    endif()
endforeach()
include("${CMAKE_CURRENT_LIST_DIR}/../DestinyConfigHeader.cmake")
file(READ "${DESTINY_FACTS}" facts)
destiny_write_config_header("${DESTINY_OUTPUT}" "${facts}" "${DESTINY_MODULE}")
