cmake_minimum_required(VERSION 3.25)
foreach(name DESTINY_MODULE_ROOT DESTINY_FACTS DESTINY_OUTPUT)
    if(NOT DEFINED ${name})
        message(FATAL_ERROR "Selection preview requires ${name}")
    endif()
endforeach()
include("${CMAKE_CURRENT_LIST_DIR}/../DestinySelection.cmake")
file(READ "${DESTINY_FACTS}" document)
destiny_flatten_facts(facts "${document}")
set(options)
if(DEFINED DESTINY_RULES_FILE)
    list(APPEND options RULES_FILE "${DESTINY_RULES_FILE}")
endif()
if(DESTINY_VALIDATE_ONLY)
    list(APPEND options VALIDATE_ONLY)
endif()
destiny_select_sources(result "${DESTINY_MODULE_ROOT}" "${facts}" ${options})
_destiny_write_if_changed("${DESTINY_OUTPUT}" "${result}\n")
