include_guard(GLOBAL)

function(_destiny_cpp_string output value)
    string(REPLACE "\\" "\\\\" value "${value}")
    string(REPLACE "\"" "\\\"" value "${value}")
    set(${output} "\"${value}\"" PARENT_SCOPE)
endfunction()

function(destiny_write_config_header output facts module)
    string(JSON fields GET "${facts}" modules "${module}")
    string(JSON count LENGTH "${fields}")
    set(DESTINY_CONFIG_DEFINITIONS "")
    if(count GREATER 0)
        math(EXPR last "${count} - 1")
        foreach(index RANGE 0 ${last})
            string(JSON name MEMBER "${fields}" ${index})
            string(JSON fact GET "${fields}" "${name}")
            string(JSON macro GET "${fact}" macro)
            string(JSON alias GET "${fact}" alias)
            string(JSON status GET "${fact}" status)
            string(JSON type GET "${fact}" type)
            set(available 0)
            set(value 0)
            if(status STREQUAL "available")
                set(available 1)
                string(JSON value GET "${fact}" value)
                if(type STREQUAL "boolean")
                    if(value)
                        set(value 1)
                    else()
                        set(value 0)
                    endif()
                endif()
            endif()
            if(type STREQUAL "integer")
                if(value STREQUAL "-9223372036854775808")
                    set(value "(-9223372036854775807LL - 1)")
                else()
                    string(APPEND value "LL")
                endif()
            elseif(type STREQUAL "string")
                if(NOT available)
                    set(value "")
                endif()
                _destiny_cpp_string(value "${value}")
            endif()
            string(APPEND DESTINY_CONFIG_DEFINITIONS "#define ${macro} ${value}\n#define ${macro}_AVAILABLE ${available}\n")
            if(alias)
                string(APPEND DESTINY_CONFIG_DEFINITIONS "#define ${alias} ${macro}\n#define ${alias}_AVAILABLE ${macro}_AVAILABLE\n")
            endif()
            if(NOT available)
                string(JSON reason GET "${fact}" reason)
                message(STATUS "Probe ${name}: ${status} (${reason}); effective capability disabled")
            endif()
        endforeach()
    endif()
    configure_file("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/templates/config.hpp.in" "${output}" @ONLY NEWLINE_STYLE UNIX)
endfunction()
