include_guard(GLOBAL)

include("${CMAKE_CURRENT_LIST_DIR}/DestinyConfigHeader.cmake")

function(destiny_prepare_facts manifest)
    set(context "{}")
    foreach(pair "system;${CMAKE_SYSTEM_NAME}" "processor;${CMAKE_SYSTEM_PROCESSOR}"
            "compiler_id;${CMAKE_CXX_COMPILER_ID}" "compiler_version;${CMAKE_CXX_COMPILER_VERSION}"
            "compiler;${CMAKE_CXX_COMPILER}" "pointer_bytes;${CMAKE_SIZEOF_VOID_P}")
        list(GET pair 0 key)
        list(GET pair 1 value)
        _destiny_json_quote(encoded "${value}")
        string(JSON context SET "${context}" "${key}" "${encoded}")
    endforeach()
    string(TOUPPER "${CMAKE_BUILD_TYPE}" configuration)
    separate_arguments(compiler_flags NATIVE_COMMAND "${CMAKE_CXX_FLAGS} ${CMAKE_CXX_FLAGS_${configuration}}")
    _destiny_project_options(options)
    list(APPEND compiler_flags ${options})
    _destiny_json_array(encoded_flags ${compiler_flags})
    string(JSON context SET "${context}" compiler_flags "${encoded_flags}")
    get_property(compilation GLOBAL PROPERTY DESTINY_COMPILE_CONTEXTS)
    string(JSON context SET "${context}" compilation_contexts "${compilation}")
    _destiny_json_quote(cache "${CMAKE_BINARY_DIR}/generated/probe-cache")
    string(JSON context SET "${context}" probe_cache "${cache}")
    _destiny_write_if_changed("${CMAKE_BINARY_DIR}/generated/probe-context.json" "${context}\n")
    set(facts_file "${CMAKE_BINARY_DIR}/generated/facts.json")
    set(option_arguments)
    if(DESTINY_OPTIONS_FILE)
        file(GLOB option_watch CONFIGURE_DEPENDS "${DESTINY_OPTIONS_FILE}")
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${DESTINY_OPTIONS_FILE}")
        if(EXISTS "${DESTINY_OPTIONS_FILE}")
            list(APPEND option_arguments --options "${DESTINY_OPTIONS_FILE}")
        endif()
    endif()
    execute_process(
        COMMAND "${Python3_EXECUTABLE}" -B -m tool.auto_define_config
            --root "${DESTINY_PROJECT_ROOT}" --inventory "${manifest}" probe
            --context "${CMAKE_BINARY_DIR}/generated/probe-context.json" --output "${facts_file}" ${option_arguments}
        WORKING_DIRECTORY "${DESTINY_PROJECT_ROOT}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE diagnostic TIMEOUT 60)
    if(NOT result STREQUAL "0")
        message(FATAL_ERROR "Probe collection failed: ${result}\n${diagnostic}")
    endif()
    file(READ "${facts_file}" facts)
    set_property(GLOBAL PROPERTY DESTINY_FACTS_JSON "${facts}")
    file(GLOB_RECURSE inputs CONFIGURE_DEPENDS
        "${DESTINY_PROJECT_ROOT}/tool/auto_define_config/*.py"
        "${DESTINY_PROJECT_ROOT}/tool/auto_define_config/providers/native/*.cpp"
        "${DESTINY_PROJECT_ROOT}/tool/build_support/*.py"
        "${DESTINY_PROJECT_ROOT}/tool/auto_define_config/define/*/fields.json")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${inputs})
    get_property(modules GLOBAL PROPERTY DESTINY_MODULES)
    set(expected)
    foreach(module IN LISTS modules)
        if(NOT module MATCHES "^define(/|$)")
            continue()
        endif()
        _destiny_key(key "${module}")
        set(root "${CMAKE_BINARY_DIR}/generated/config/${key}")
        set(header "${root}/destiny/${module}/cmake_config.hpp")
        if(EXISTS "${DESTINY_SOURCE_ROOT}/${module}/include/cmake_config.hpp")
            message(FATAL_ERROR "Public header collides with generated cmake_config.hpp: ${module}")
        endif()
        destiny_write_config_header("${header}" "${facts}" "${module}")
        _destiny_set("${module}" CONFIG_ROOT "${root}")
        list(APPEND expected "${header}")
    endforeach()
    file(GLOB_RECURSE generated LIST_DIRECTORIES FALSE "${CMAKE_BINARY_DIR}/generated/config/*")
    foreach(old IN LISTS generated)
        if(NOT old IN_LIST expected)
            file(REMOVE "${old}")
        endif()
    endforeach()
endfunction()
