include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/DestinyExpressions.cmake")

function(_destiny_source_condition output why source facts aliases)
    get_filename_component(filename "${source}" NAME)
    if(filename MATCHES "_while_")
        if(NOT filename MATCHES "^.+_while_([A-Za-z][A-Za-z0-9_.]*)\\.cpp$")
            message(FATAL_ERROR "Malformed conditional filename: ${source}")
        endif()
        _destiny_json_quote(name "${CMAKE_MATCH_1}")
        destiny_evaluate_condition(value reason "{\"ref\":${name}}" "${facts}" "${aliases}")
    else()
        set(value TRUE)
        set(reason "Unconditional source")
    endif()
    set(${output} "${value}" PARENT_SCOPE)
    set(${why} "${reason}" PARENT_SCOPE)
endfunction()

function(_destiny_source_record output source selected reason group)
    set(record "{}")
    foreach(key source reason group)
        _destiny_json_quote(encoded "${${key}}")
        string(JSON record SET "${record}" "${key}" "${encoded}")
    endforeach()
    if(selected)
        set(selected true)
    else()
        set(selected false)
    endif()
    string(JSON record SET "${record}" selected "${selected}")
    set(${output} "${record}" PARENT_SCOPE)
endfunction()

function(destiny_select_sources output module_root facts)
    cmake_parse_arguments(S "VALIDATE_ONLY" "RULES_FILE" "" ${ARGN})
    if(S_UNPARSED_ARGUMENTS OR S_KEYWORDS_MISSING_VALUES)
        message(FATAL_ERROR "Invalid source-selection options")
    endif()
    set(watch)
    if(NOT CMAKE_SCRIPT_MODE_FILE)
        set(watch CONFIGURE_DEPENDS)
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${module_root}/source_rules.json")
        file(GLOB rule_watch CONFIGURE_DEPENDS "${module_root}/source_rules.json")
    endif()
    file(GLOB_RECURSE sources ${watch} RELATIVE "${module_root}" "${module_root}/src/*.cpp")
    list(SORT sources)
    set(rules "{\"schema_version\":1,\"aliases\":{},\"groups\":[]}")
    set(rule_file "${module_root}/source_rules.json")
    if(DEFINED S_RULES_FILE)
        set(rule_file "${S_RULES_FILE}")
    endif()
    if(EXISTS "${rule_file}")
        file(READ "${rule_file}" rules)
    endif()
    _destiny_members("${rules}" "schema_version;aliases;groups" "" "Source rules")
    _destiny_expect_type("${rules}" NUMBER schema_version)
    string(JSON version GET "${rules}" schema_version)
    if(NOT version EQUAL 1)
        message(FATAL_ERROR "Source rules require schema_version 1")
    endif()
    _destiny_expect_type("${rules}" OBJECT aliases)
    _destiny_expect_type("${rules}" ARRAY groups)
    string(JSON aliases GET "${rules}" aliases)
    string(JSON count LENGTH "${aliases}")
    if(count GREATER 0)
        math(EXPR last "${count} - 1")
        foreach(index RANGE 0 ${last})
            string(JSON alias MEMBER "${aliases}" ${index})
            string(JSON unused ERROR_VARIABLE unknown GET "${facts}" "${alias}")
            if(NOT alias MATCHES "^[A-Za-z][A-Za-z0-9_]*$" OR NOT unknown OR alias MATCHES "^(TRUE|FALSE|true|false)$")
                message(FATAL_ERROR "Invalid, reserved or shadowing local alias: ${alias}")
            endif()
            _destiny_json_quote(name "${alias}")
            destiny_evaluate_condition(value reason "{\"ref\":${name}}" "${facts}" "${aliases}")
        endforeach()
    endif()
    # Validate every source condition, including candidates that lose priority.
    foreach(source IN LISTS sources)
        if(source MATCHES "[;\n\r]")
            message(FATAL_ERROR "Unsupported source filename: ${source}")
        endif()
        file(REAL_PATH "${module_root}/src" source_root)
        file(REAL_PATH "${module_root}/${source}" resolved)
        cmake_path(IS_PREFIX source_root "${resolved}" NORMALIZE within)
        if(NOT within)
            message(FATAL_ERROR "Source escapes module src directory: ${source}")
        endif()
        _destiny_source_condition(value why "${source}" "${facts}" "${aliases}")
    endforeach()
    set(records "{}")
    set(groups "{}")
    set(claimed)
    set(group_names)
    string(JSON count LENGTH "${rules}" groups)
    if(count GREATER 0)
        math(EXPR last "${count} - 1")
        foreach(index RANGE 0 ${last})
            string(JSON group GET "${rules}" groups ${index})
            _destiny_members("${group}" "name;candidates" "" "Implementation group")
            _destiny_expect_type("${group}" STRING name)
            _destiny_expect_type("${group}" ARRAY candidates)
            string(JSON name GET "${group}" name)
            if(NOT name MATCHES "^[A-Za-z][A-Za-z0-9_]*$" OR name IN_LIST group_names)
                message(FATAL_ERROR "Invalid or duplicate implementation group: ${name}")
            endif()
            list(APPEND group_names "${name}")
            set(winner "")
            set(candidate_names)
            set(candidate_reasons "")
            string(JSON candidates LENGTH "${group}" candidates)
            if(candidates EQUAL 0)
                message(FATAL_ERROR "Implementation group ${name} has no candidates")
            endif()
            math(EXPR candidate_last "${candidates} - 1")
            foreach(candidate_index RANGE 0 ${candidate_last})
                string(JSON candidate GET "${group}" candidates ${candidate_index})
                _destiny_members("${candidate}" "name;when;sources" "" "Implementation candidate")
                _destiny_expect_type("${candidate}" STRING name)
                _destiny_expect_type("${candidate}" ARRAY sources)
                string(JSON candidate_name GET "${candidate}" name)
                if(NOT candidate_name MATCHES "^[A-Za-z][A-Za-z0-9_]*$" OR candidate_name IN_LIST candidate_names)
                    message(FATAL_ERROR "Invalid or duplicate candidate in ${name}: ${candidate_name}")
                endif()
                list(APPEND candidate_names "${candidate_name}")
                _destiny_json_extract(condition "${candidate}" when)
                destiny_evaluate_condition(eligible reason "${condition}" "${facts}" "${aliases}")
                string(JSON member_count LENGTH "${candidate}" sources)
                if(member_count EQUAL 0)
                    message(FATAL_ERROR "Candidate ${name}/${candidate_name} must list sources")
                endif()
                set(members)
                math(EXPR member_last "${member_count} - 1")
                foreach(member_index RANGE 0 ${member_last})
                    _destiny_expect_type("${candidate}" STRING sources ${member_index})
                    string(JSON member GET "${candidate}" sources ${member_index})
                    if(NOT member IN_LIST sources OR member IN_LIST claimed)
                        message(FATAL_ERROR "Missing or multiply owned source in ${name}/${candidate_name}: ${member}")
                    endif()
                    list(APPEND claimed "${member}")
                    list(APPEND members "${member}")
                    _destiny_source_condition(member_value member_reason "${member}" "${facts}" "${aliases}")
                    if(NOT member_value)
                        set(eligible FALSE)
                        string(APPEND reason "; ${member}: ${member_reason}")
                    endif()
                endforeach()
                set(selected FALSE)
                if(eligible AND winner STREQUAL "")
                    set(winner "${candidate_name}")
                    set(selected TRUE)
                    set(reason "Selected ${name}/${candidate_name}: ${reason}")
                elseif(eligible)
                    set(reason "Lower preference than ${name}/${winner}")
                endif()
                string(APPEND candidate_reasons "\n  ${candidate_name}: ${reason}")
                foreach(member IN LISTS members)
                    _destiny_source_record(record "${member}" "${selected}" "${reason}" "${name}")
                    string(JSON records SET "${records}" "${member}" "${record}")
                endforeach()
            endforeach()
            if(winner STREQUAL "" AND NOT S_VALIDATE_ONLY)
                message(FATAL_ERROR "No eligible implementation for required group ${name}:${candidate_reasons}")
            endif()
            _destiny_json_quote(encoded "${winner}")
            string(JSON groups SET "${groups}" "${name}" "${encoded}")
        endforeach()
    endif()
    foreach(source IN LISTS sources)
        if(NOT source IN_LIST claimed)
            _destiny_source_condition(value why "${source}" "${facts}" "${aliases}")
            _destiny_source_record(record "${source}" "${value}" "${why}" "")
            string(JSON records SET "${records}" "${source}" "${record}")
        endif()
    endforeach()
    set(result "{\"schema_version\":1}")
    string(JSON result SET "${result}" sources "${records}")
    string(JSON result SET "${result}" groups "${groups}")
    set(${output} "${result}" PARENT_SCOPE)
endfunction()

function(destiny_flatten_facts output document)
    string(JSON version GET "${document}" schema_version)
    if(NOT version EQUAL 1)
        message(FATAL_ERROR "Facts document requires schema_version 1")
    endif()
    string(JSON modules GET "${document}" modules)
    string(JSON count LENGTH "${modules}")
    set(result "{}")
    if(count GREATER 0)
        math(EXPR last "${count} - 1")
        foreach(index RANGE 0 ${last})
            string(JSON module MEMBER "${modules}" ${index})
            string(JSON fields GET "${modules}" "${module}")
            string(JSON fields_count LENGTH "${fields}")
            if(fields_count GREATER 0)
                math(EXPR fields_last "${fields_count} - 1")
                foreach(field_index RANGE 0 ${fields_last})
                    string(JSON field MEMBER "${fields}" ${field_index})
                    string(JSON fact GET "${fields}" "${field}")
                    string(JSON existing ERROR_VARIABLE missing GET "${result}" "${field}")
                    if(NOT missing)
                        message(FATAL_ERROR "Duplicate field in facts: ${field}")
                    endif()
                    string(JSON result SET "${result}" "${field}" "${fact}")
                endforeach()
            endif()
        endforeach()
    endif()
    set(${output} "${result}" PARENT_SCOPE)
endfunction()
