include_guard(GLOBAL)

function(_destiny_public_headers path target scope)
    set(root "${DESTINY_SOURCE_ROOT}/${path}/include")
    _destiny_key(key "${path}")
    set(mapping "${CMAKE_BINARY_DIR}/generated/include/${key}")
    file(GLOB_RECURSE headers CONFIGURE_DEPENDS LIST_DIRECTORIES FALSE "${root}/*")
    set(expected)
    foreach(header IN LISTS headers)
        file(RELATIVE_PATH relative "${root}" "${header}")
        set(forward "${mapping}/destiny/${path}/${relative}")
        # Absolute forwarding preserves sibling includes in the maintained header.
        string(REPLACE "\\" "/" include_path "${header}")
        if(include_path MATCHES "[\"\n\r]")
            message(FATAL_ERROR "Header path cannot be represented in an include: ${header}")
        endif()
        _destiny_write_if_changed("${forward}" "#pragma once\n#include \"${include_path}\"\n")
        list(APPEND expected "${forward}")
    endforeach()
    file(GLOB_RECURSE old LIST_DIRECTORIES FALSE "${mapping}/*")
    foreach(stale IN LISTS old)
        if(NOT stale IN_LIST expected)
            file(REMOVE "${stale}")
        endif()
    endforeach()
    target_include_directories("${target}" ${scope} "${mapping}")
    _destiny_get(config_root "${path}" CONFIG_ROOT)
    if(config_root)
        target_include_directories("${target}" ${scope} "${config_root}")
    endif()
endfunction()

