include_guard(GLOBAL)
include(CheckCXXSourceCompiles)
include("${CMAKE_CURRENT_LIST_DIR}/DestinyPlatform.cmake")

function(_destiny_compiler_context output)
    set(context "{}")
    file(SHA256 "${CMAKE_CXX_COMPILER}" compiler_digest)
    foreach(name CMAKE_VERSION CMAKE_CXX_COMPILER CMAKE_CXX_COMPILER_ID
            CMAKE_CXX_COMPILER_VERSION CMAKE_CXX_COMPILER_ARG1 CMAKE_CXX_COMPILER_TARGET
            CMAKE_CXX_COMPILER_EXTERNAL_TOOLCHAIN CMAKE_SYSTEM_NAME CMAKE_SYSTEM_PROCESSOR
            CMAKE_SIZEOF_VOID_P CMAKE_SYSROOT CMAKE_SYSROOT_COMPILE CMAKE_OSX_SYSROOT
            CMAKE_OSX_ARCHITECTURES CMAKE_OSX_DEPLOYMENT_TARGET CMAKE_BUILD_TYPE
            CMAKE_CXX_FLAGS CMAKE_AR CMAKE_RANLIB)
        _destiny_json_quote(value "${${name}}")
        string(JSON context SET "${context}" "${name}" "${value}")
    endforeach()
    foreach(name CPATH CPLUS_INCLUDE_PATH COMPILER_PATH GCC_EXEC_PREFIX SDKROOT
            MACOSX_DEPLOYMENT_TARGET)
        _destiny_json_quote(value "$ENV{${name}}")
        string(JSON context SET "${context}" "env_${name}" "${value}")
    endforeach()
    string(TOUPPER "${CMAKE_BUILD_TYPE}" configuration)
    _destiny_json_quote(value "${CMAKE_CXX_FLAGS_${configuration}}")
    string(JSON context SET "${context}" configuration_flags "${value}")
    _destiny_json_quote(value "${compiler_digest}")
    string(JSON context SET "${context}" compiler_digest "${value}")
    _destiny_project_options(options)
    _destiny_system_definitions(definitions)
    _destiny_json_array(value ${options})
    string(JSON context SET "${context}" project_options "${value}")
    _destiny_json_array(value ${definitions})
    string(JSON context SET "${context}" system_definitions "${value}")
    set(${output} "${context}" PARENT_SCOPE)
endfunction()

function(_destiny_require_dialect output module standard compiler_context)
    if(NOT "cxx_std_${standard}" IN_LIST CMAKE_CXX_COMPILE_FEATURES)
        message(FATAL_ERROR "Compiler ${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION} cannot provide C++${standard} required by ${module}")
    endif()
    set(minimum_98 199711)
    set(minimum_11 201103)
    set(minimum_14 201402)
    set(minimum_17 201703)
    set(minimum_20 202002)
    set(minimum_23 202003)
    set(minimum_26 202303)
    set(source "#if __cplusplus < ${minimum_${standard}}L
#error Required minimum C++ mode is not active
#endif
int destiny_dialect_probe() { return 0; }
")
    set(context "${compiler_context}")
    string(JSON context SET "${context}" minimum_standard ${standard})
    string(JSON context SET "${context}" extensions false)
    string(SHA256 key "${context}
${source}")
    set(check "DESTINY_DIALECT_${key}")
    set(CMAKE_CXX_STANDARD "${standard}")
    set(CMAKE_CXX_STANDARD_REQUIRED YES)
    set(CMAKE_CXX_EXTENSIONS NO)
    set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
    set(CMAKE_TRY_COMPILE_CONFIGURATION "${CMAKE_BUILD_TYPE}")
    set(CMAKE_REQUIRED_QUIET YES)
    set(CMAKE_REQUIRED_INCLUDES)
    set(CMAKE_REQUIRED_LIBRARIES)
    set(CMAKE_REQUIRED_LINK_OPTIONS)
    _destiny_project_options(options)
    list(JOIN options " " CMAKE_REQUIRED_FLAGS)
    _destiny_system_definitions(definitions)
    set(CMAKE_REQUIRED_DEFINITIONS)
    foreach(definition IN LISTS definitions)
        list(APPEND CMAKE_REQUIRED_DEFINITIONS "-D${definition}")
    endforeach()
    check_cxx_source_compiles("${source}" "${check}")
    if(NOT ${check})
        message(FATAL_ERROR "C++${standard} compilation context is unavailable for ${module}. Check the selected compiler, target architecture and flags in the CMake configure log. DESTINY_NATIVE_OPTIMIZATION=OFF explicitly requests a portable baseline.")
    endif()
    _destiny_json_quote(value "${key}")
    string(JSON context SET "${context}" cache_key "${value}")
    string(JSON context SET "${context}" standard_available true)
    set(${output} "${context}" PARENT_SCOPE)
endfunction()

function(destiny_prepare_compile_contexts)
    _destiny_compiler_context(compiler_context)
    get_property(modules GLOBAL PROPERTY DESTINY_MODULES)
    set(contexts "{}")
    foreach(module IN LISTS modules)
        _destiny_get(standard "${module}" EFFECTIVE_CXX)
        _destiny_require_dialect(context "${module}" "${standard}" "${compiler_context}")
        _destiny_set("${module}" COMPILE_CONTEXT "${context}")
        string(JSON contexts SET "${contexts}" "${module}" "${context}")
    endforeach()
    set_property(GLOBAL PROPERTY DESTINY_COMPILE_CONTEXTS "${contexts}")
endfunction()
