include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/DestinyPlatform.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/DestinyHeaders.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/DestinyPrograms.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/DestinySelection.cmake")

function(_destiny_target_name output path)
    _destiny_key(key "${path}")
    string(REPLACE "/" "_" name "${path}")
    string(SUBSTRING "${key}" 0 12 suffix)
    set(${output} "destiny_${name}_${suffix}" PARENT_SCOPE)
endfunction()

function(_destiny_compile_policy target standard)
    target_compile_features("${target}" PRIVATE "cxx_std_${standard}")
    set_target_properties("${target}" PROPERTIES CXX_STANDARD "${standard}"
        CXX_STANDARD_REQUIRED YES CXX_EXTENSIONS NO)
    _destiny_project_options(options)
    target_compile_options("${target}" PRIVATE ${options})
endfunction()

function(_destiny_materialize_module path)
    _destiny_target_name(target "${path}")
    _destiny_get(kind "${path}" KIND)
    _destiny_get(impl "${path}" CXX)
    _destiny_get(public "${path}" PUBLIC_CXX)
    _destiny_get(effective "${path}" EFFECTIVE_CXX)
    get_property(document GLOBAL PROPERTY DESTINY_FACTS_JSON)
    destiny_flatten_facts(facts "${document}")
    destiny_select_sources(selection "${DESTINY_SOURCE_ROOT}/${path}" "${facts}")
    set(sources)
    string(JSON records GET "${selection}" sources)
    string(JSON count LENGTH "${records}")
    if(count GREATER 0)
        math(EXPR last "${count} - 1")
        foreach(index RANGE 0 ${last})
            string(JSON relative MEMBER "${records}" ${index})
            string(JSON selected GET "${records}" "${relative}" selected)
            if(selected)
                list(APPEND sources "${DESTINY_SOURCE_ROOT}/${path}/${relative}")
            endif()
        endforeach()
    endif()
    _destiny_set("${path}" SELECTION "${selection}")
    if(kind STREQUAL "AUTO")
        if(sources)
            set(kind STATIC)
        else()
            set(kind INTERFACE)
        endif()
    endif()
    if(kind STREQUAL "STATIC" AND NOT sources)
        message(FATAL_ERROR "STATIC module has no implementation sources: ${path}")
    endif()
    if(kind STREQUAL "INTERFACE")
        if(sources OR NOT impl STREQUAL public)
            message(FATAL_ERROR "INTERFACE module has implementation sources or inconsistent standards: ${path}")
        endif()
        add_library("${target}" INTERFACE)
        set(include_scope INTERFACE)
    else()
        add_library("${target}" STATIC ${sources})
        _destiny_compile_policy("${target}" "${effective}")
        target_include_directories("${target}" PRIVATE "${DESTINY_SOURCE_ROOT}/${path}/src")
        set_target_properties("${target}" PROPERTIES
            ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/lib/${path}")
        set(include_scope PUBLIC)
    endif()
    _destiny_system_usage("${target}" "${include_scope}")
    target_compile_features("${target}" INTERFACE "cxx_std_${public}")
    string(REPLACE "/" "::" alias "${path}")
    add_library("destiny::${alias}" ALIAS "${target}")
    foreach(scope PUBLIC PRIVATE INTERFACE)
        _destiny_get(deps "${path}" "DEP_${scope}")
        if(kind STREQUAL "INTERFACE" AND deps AND scope STREQUAL "PRIVATE")
            message(FATAL_ERROR "Header-only module cannot have PRIVATE dependencies: ${path}")
        endif()
        foreach(dep IN LISTS deps)
            _destiny_target_name(dependency "${dep}")
            if(kind STREQUAL "INTERFACE")
                target_link_libraries("${target}" INTERFACE "${dependency}")
            else()
                target_link_libraries("${target}" ${scope} "${dependency}")
            endif()
        endforeach()
    endforeach()
    _destiny_public_headers("${path}" "${target}" "${include_scope}")
    _destiny_set("${path}" TARGET "${target}")
    _destiny_set("${path}" SOURCES "${sources}")
    set_property(GLOBAL APPEND PROPERTY DESTINY_BUILD_TARGETS "${target}")
    _destiny_module_programs("${path}")
endfunction()
