include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/DestinyJson.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/DestinyProgramRegistry.cmake")

function(_destiny_key output path)
    string(SHA256 key "${path}")
    set(${output} "${key}" PARENT_SCOPE)
endfunction()

function(_destiny_set path field)
    _destiny_key(key "${path}")
    set_property(GLOBAL PROPERTY "DESTINY_${key}_${field}" "${ARGN}")
endfunction()

function(_destiny_get output path field)
    _destiny_key(key "${path}")
    get_property(value GLOBAL PROPERTY "DESTINY_${key}_${field}")
    set(${output} "${value}" PARENT_SCOPE)
endfunction()

function(_destiny_max_standard output left right)
    set(standards 98 11 14 17 20 23 26)
    list(FIND standards "${left}" left_rank)
    list(FIND standards "${right}" right_rank)
    if(left_rank LESS 0 OR right_rank LESS 0)
        message(FATAL_ERROR "Unsupported C++ standard: ${left} or ${right}")
    endif()
    if(left_rank LESS right_rank)
        set(${output} "${right}" PARENT_SCOPE)
    else()
        set(${output} "${left}" PARENT_SCOPE)
    endif()
endfunction()

function(destiny_register_layers)
    if(NOT ARGN)
        message(FATAL_ERROR "At least one layer must be registered")
    endif()
    set(seen)
    foreach(layer IN LISTS ARGN)
        if(NOT layer MATCHES "^[A-Za-z][A-Za-z0-9_]*$" OR layer IN_LIST seen)
            message(FATAL_ERROR "Invalid or duplicate layer: ${layer}")
        endif()
        list(APPEND seen "${layer}")
    endforeach()
    get_property(modules GLOBAL PROPERTY DESTINY_MODULES)
    if(modules)
        message(FATAL_ERROR "Register layers before modules")
    endif()
    set_property(GLOBAL PROPERTY DESTINY_LAYERS "${seen}")
endfunction()

function(destiny_add_module)
    if(NOT DEFINED _destiny_module_path)
        message(FATAL_ERROR "destiny_add_module requires a discovered module file")
    endif()
    cmake_parse_arguments(P "" "CXX_STANDARD;PUBLIC_CXX_STANDARD" "" ${ARGN})
    set(kind AUTO)
    if(P_UNPARSED_ARGUMENTS)
        list(LENGTH P_UNPARSED_ARGUMENTS count)
        if(NOT count EQUAL 1 OR NOT P_UNPARSED_ARGUMENTS MATCHES "^(AUTO|STATIC|INTERFACE)$")
            message(FATAL_ERROR "Unknown module arguments: ${P_UNPARSED_ARGUMENTS}")
        endif()
        set(kind "${P_UNPARSED_ARGUMENTS}")
    endif()
    if(P_KEYWORDS_MISSING_VALUES)
        message(FATAL_ERROR "Missing module argument values: ${P_KEYWORDS_MISSING_VALUES}")
    endif()
    get_property(modules GLOBAL PROPERTY DESTINY_MODULES)
    if(_destiny_module_path IN_LIST modules)
        message(FATAL_ERROR "Module registered twice: ${_destiny_module_path}")
    endif()
    if(NOT DEFINED P_CXX_STANDARD)
        set(P_CXX_STANDARD 20)
    endif()
    if(NOT DEFINED P_PUBLIC_CXX_STANDARD)
        set(P_PUBLIC_CXX_STANDARD "${P_CXX_STANDARD}")
    endif()
    _destiny_max_standard(unused "${P_CXX_STANDARD}" "${P_PUBLIC_CXX_STANDARD}")
    if(kind STREQUAL "INTERFACE" AND NOT P_CXX_STANDARD STREQUAL P_PUBLIC_CXX_STANDARD)
        message(FATAL_ERROR "Header-only standard requirements differ: ${_destiny_module_path}")
    endif()
    _destiny_set("${_destiny_module_path}" PROGRAM_NAMES "")
    _destiny_set("${_destiny_module_path}" KIND "${kind}")
    _destiny_set("${_destiny_module_path}" CXX "${P_CXX_STANDARD}")
    _destiny_set("${_destiny_module_path}" PUBLIC_CXX "${P_PUBLIC_CXX_STANDARD}")
    foreach(scope PUBLIC PRIVATE INTERFACE)
        _destiny_set("${_destiny_module_path}" "DEP_${scope}" "")
    endforeach()
    set_property(GLOBAL APPEND PROPERTY DESTINY_MODULES "${_destiny_module_path}")
endfunction()

function(destiny_depends scope)
    get_property(modules GLOBAL PROPERTY DESTINY_MODULES)
    if(NOT DEFINED _destiny_module_path OR NOT _destiny_module_path IN_LIST modules)
        message(FATAL_ERROR "Declare the module before its dependencies")
    endif()
    if(NOT scope MATCHES "^(PUBLIC|PRIVATE|INTERFACE)$" OR NOT ARGN)
        message(FATAL_ERROR "Use destiny_depends(PUBLIC|PRIVATE|INTERFACE module ...)")
    endif()
    _destiny_get(deps "${_destiny_module_path}" "DEP_${scope}")
    list(APPEND deps ${ARGN})
    list(REMOVE_DUPLICATES deps)
    _destiny_set("${_destiny_module_path}" "DEP_${scope}" "${deps}")
endfunction()

function(destiny_collect_modules)
    set_property(GLOBAL PROPERTY DESTINY_MODULES "")
    if(EXISTS "${DESTINY_PROJECT_ROOT}/cmake/DestinyLayers.cmake")
        include("${DESTINY_PROJECT_ROOT}/cmake/DestinyLayers.cmake")
    else()
        include("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/DestinyLayers.cmake")
    endif()
    set(watch)
    if(NOT CMAKE_SCRIPT_MODE_FILE)
        set(watch CONFIGURE_DEPENDS)
    endif()
    file(GLOB_RECURSE entries ${watch} "${DESTINY_SOURCE_ROOT}/*/CMakeLists.txt")
    list(SORT entries)
    get_property(layers GLOBAL PROPERTY DESTINY_LAYERS)
    foreach(entry IN LISTS entries)
        get_filename_component(directory "${entry}" DIRECTORY)
        file(RELATIVE_PATH _destiny_module_path "${DESTINY_SOURCE_ROOT}" "${directory}")
        if(NOT _destiny_module_path MATCHES "^[A-Za-z][A-Za-z0-9_-]*(/[A-Za-z][A-Za-z0-9_-]*)*$")
            message(FATAL_ERROR "Invalid module path: ${_destiny_module_path}")
        endif()
        string(REGEX REPLACE "/.*$" "" layer "${_destiny_module_path}")
        if(NOT layer IN_LIST layers)
            message(FATAL_ERROR "Unknown layer in ${_destiny_module_path}: ${layer}")
        endif()
        include("${entry}")
    endforeach()
    get_property(modules GLOBAL PROPERTY DESTINY_MODULES)
    set(ordered)
    foreach(layer IN LISTS layers)
        foreach(path IN LISTS modules)
            if(path MATCHES "^${layer}(/|$)")
                list(APPEND ordered "${path}")
            endif()
        endforeach()
    endforeach()
    set_property(GLOBAL PROPERTY DESTINY_MODULES "${ordered}")
    _destiny_resolve_dependencies()
    _destiny_resolve_programs()
endfunction()

function(_destiny_resolve_dependencies)
    get_property(modules GLOBAL PROPERTY DESTINY_MODULES)
    get_property(layers GLOBAL PROPERTY DESTINY_LAYERS)
    foreach(path IN LISTS modules)
        string(REGEX REPLACE "/.*$" "" layer "${path}")
        list(FIND layers "${layer}" rank)
        _destiny_get(impl "${path}" CXX)
        _destiny_get(public "${path}" PUBLIC_CXX)
        foreach(scope PUBLIC PRIVATE INTERFACE)
            _destiny_get(deps "${path}" "DEP_${scope}")
            foreach(dep IN LISTS deps)
                if(NOT dep IN_LIST modules)
                    message(FATAL_ERROR "Unknown dependency ${dep} of ${path}")
                endif()
                string(REGEX REPLACE "/.*$" "" dep_layer "${dep}")
                list(FIND layers "${dep_layer}" dep_rank)
                if(NOT dep_rank LESS rank)
                    message(FATAL_ERROR "Dependency must point to a strictly lower layer: ${path} -> ${dep}")
                endif()
                _destiny_get(requirement "${dep}" EFFECTIVE_PUBLIC_CXX)
                if(NOT scope STREQUAL "INTERFACE")
                    _destiny_max_standard(impl "${impl}" "${requirement}")
                endif()
                if(NOT scope STREQUAL "PRIVATE")
                    _destiny_max_standard(public "${public}" "${requirement}")
                endif()
            endforeach()
        endforeach()
        _destiny_max_standard(impl "${impl}" "${public}")
        _destiny_set("${path}" EFFECTIVE_CXX "${impl}")
        _destiny_set("${path}" EFFECTIVE_PUBLIC_CXX "${public}")
    endforeach()
endfunction()

function(destiny_write_inventory output)
    get_property(modules GLOBAL PROPERTY DESTINY_MODULES)
    get_property(layers GLOBAL PROPERTY DESTINY_LAYERS)
    _destiny_json_array(layer_json ${layers})
    _destiny_json_quote(root "${DESTINY_PROJECT_ROOT}")
    set(result "{\"schema_version\":1,\"modules\":[]}")
    string(JSON result SET "${result}" root "${root}")
    string(JSON result SET "${result}" layers "${layer_json}")
    set(index 0)
    foreach(path IN LISTS modules)
        _destiny_json_quote(encoded "${path}")
        set(module "{}")
        string(JSON module SET "${module}" path "${encoded}")
        foreach(pair "KIND;kind" "CXX;cxx_standard" "PUBLIC_CXX;public_cxx_standard" "EFFECTIVE_CXX;effective_cxx_standard" "EFFECTIVE_PUBLIC_CXX;effective_public_cxx_standard")
            list(GET pair 0 property)
            list(GET pair 1 name)
            _destiny_get(value "${path}" "${property}")
            _destiny_json_quote(value "${value}")
            string(JSON module SET "${module}" "${name}" "${value}")
        endforeach()
        set(dependencies "{}")
        foreach(scope PUBLIC PRIVATE INTERFACE)
            _destiny_get(deps "${path}" "DEP_${scope}")
            _destiny_json_array(deps ${deps})
            string(JSON dependencies SET "${dependencies}" "${scope}" "${deps}")
        endforeach()
        string(JSON module SET "${module}" dependencies "${dependencies}")
        set(program_json "[]")
        set(program_index 0)
        _destiny_get(programs "${path}" PROGRAM_NAMES)
        foreach(id IN LISTS programs)
            _destiny_json_quote(encoded "${id}")
            set(program "{}")
            string(JSON program SET "${program}" id "${encoded}")
            foreach(field SOURCES DEPENDS)
                _destiny_get(values "${path}" "PROGRAM_${id}_${field}")
                _destiny_json_array(values ${values})
                string(TOLOWER "${field}" name)
                string(JSON program SET "${program}" "${name}" "${values}")
            endforeach()
            _destiny_get(standard "${path}" "PROGRAM_${id}_EFFECTIVE_CXX")
            string(JSON program SET "${program}" effective_cxx_standard ${standard})
            _destiny_get(custom_main "${path}" "PROGRAM_${id}_CUSTOM_MAIN")
            if(custom_main)
                set(custom_main true)
            else()
                set(custom_main false)
            endif()
            string(JSON program SET "${program}" custom_main "${custom_main}")
            string(JSON program_json SET "${program_json}" ${program_index} "${program}")
            math(EXPR program_index "${program_index} + 1")
        endforeach()
        string(JSON module SET "${module}" programs "${program_json}")
        string(JSON result SET "${result}" modules ${index} "${module}")
        math(EXPR index "${index} + 1")
    endforeach()
    _destiny_write_if_changed("${output}" "${result}\n")
endfunction()
