include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/DestinyRuntime.cmake")

function(_destiny_require_gtest)
    if(TARGET GTest::gtest_main)
        return()
    endif()
    set(source "${DESTINY_PROJECT_ROOT}/thirdLib/googletest")
    if(NOT EXISTS "${source}/CMakeLists.txt")
        message(FATAL_ERROR "Vendored GoogleTest is required for enabled tests: ${source}")
    endif()
    set(BUILD_GMOCK OFF CACHE BOOL "" FORCE)
    set(INSTALL_GTEST OFF CACHE BOOL "" FORCE)
    set(gtest_build_tests OFF CACHE BOOL "" FORCE)
    set(gtest_build_samples OFF CACHE BOOL "" FORCE)
    add_subdirectory("${source}" "${CMAKE_BINARY_DIR}/.obj/thirdLib/googletest" EXCLUDE_FROM_ALL)
    _destiny_system_usage(gtest PUBLIC)
endfunction()

function(_destiny_create_program path category stem)
    cmake_parse_arguments(P "CUSTOM_MAIN" "CXX_STANDARD" "SOURCES;DEPENDS" ${ARGN})
    _destiny_get(module "${path}" TARGET)
    _destiny_get(standard "${path}" EFFECTIVE_CXX)
    if(P_CXX_STANDARD)
        _destiny_max_standard(standard "${standard}" "${P_CXX_STANDARD}")
    endif()
    _destiny_target_name(target "${path}/${category}/${stem}")
    if(TARGET "${target}")
        message(FATAL_ERROR "Program output name collision: ${path}/${category}/${stem}")
    endif()
    add_executable("${target}" ${P_SOURCES})
    target_link_libraries("${target}" PRIVATE "${module}")
    foreach(dep IN LISTS P_DEPENDS)
        _destiny_target_name(dependency "${dep}")
        target_link_libraries("${target}" PRIVATE "${dependency}")
    endforeach()
    _destiny_compile_policy("${target}" "${standard}")
    set_target_properties("${target}" PROPERTIES OUTPUT_NAME "${stem}"
        RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/${path}/${category}")
    _destiny_stage_runtime("${target}")
    if(category STREQUAL "test")
        _destiny_require_gtest()
        if(P_CUSTOM_MAIN)
            target_link_libraries("${target}" PRIVATE GTest::gtest)
        else()
            target_link_libraries("${target}" PRIVATE GTest::gtest_main)
        endif()
        include(GoogleTest)
        set(discovery_directory "${DESTINY_PROJECT_ROOT}")
        if(CMAKE_VERSION VERSION_GREATER_EQUAL "3.29")
            # Keep discovery metadata out of source while the executable still runs at the root.
            set(discovery_directory "${CMAKE_BINARY_DIR}/reports/discovery/${target}")
            file(MAKE_DIRECTORY "${discovery_directory}")
            set_property(TARGET "${target}" PROPERTY TEST_LAUNCHER
                "${CMAKE_COMMAND};-E;chdir;${DESTINY_PROJECT_ROOT}")
        endif()
        gtest_discover_tests("${target}" DISCOVERY_MODE PRE_TEST
            WORKING_DIRECTORY "${discovery_directory}"
            TEST_LIST "${target}_TESTS"
            TEST_PREFIX "${path}/${stem}/"
            XML_OUTPUT_DIR "${CMAKE_BINARY_DIR}/reports/test/${path}/${stem}")
        set(properties_script "${CMAKE_CURRENT_BINARY_DIR}/${target}-test-properties.cmake")
        set(test_properties "if(DEFINED ${target}_TESTS)\n    set_tests_properties(\${${target}_TESTS} PROPERTIES WORKING_DIRECTORY [==[${DESTINY_PROJECT_ROOT}]==])\nendif()\n")
        _destiny_write_if_changed("${properties_script}" "${test_properties}")
        set_property(DIRECTORY APPEND PROPERTY TEST_INCLUDE_FILES "${properties_script}")
    endif()
    set_property(GLOBAL APPEND PROPERTY DESTINY_BUILD_TARGETS "${target}")
    set_property(GLOBAL APPEND PROPERTY DESTINY_PROGRAMS "${path}|${category}|${target}|${stem}")
endfunction()

function(_destiny_module_programs path)
    _destiny_get(explicit "${path}" PROGRAM_NAMES)
    foreach(category test bench demo)
        if((category STREQUAL "test" AND NOT DESTINY_BUILD_TESTS) OR
           (category STREQUAL "bench" AND NOT DESTINY_BUILD_BENCHMARKS) OR
           (category STREQUAL "demo" AND NOT DESTINY_BUILD_DEMOS))
            continue()
        endif()
        set(assigned)
        foreach(id IN LISTS explicit)
            if(NOT id MATCHES "^${category}/")
                continue()
            endif()
            string(REGEX REPLACE "^[^/]+/" "" name "${id}")
            _destiny_get(relative_sources "${path}" "PROGRAM_${id}_SOURCES")
            _destiny_get(dependencies "${path}" "PROGRAM_${id}_DEPENDS")
            _destiny_get(standard "${path}" "PROGRAM_${id}_EFFECTIVE_CXX")
            _destiny_get(custom "${path}" "PROGRAM_${id}_CUSTOM_MAIN")
            set(flags)
            if(custom)
                list(APPEND flags CUSTOM_MAIN)
            endif()
            set(sources)
            foreach(source IN LISTS relative_sources)
                set(absolute "${DESTINY_SOURCE_ROOT}/${path}/${source}")
                list(APPEND sources "${absolute}")
                list(APPEND assigned "${absolute}")
            endforeach()
            _destiny_create_program("${path}" "${category}" "${name}"
                SOURCES ${sources} DEPENDS ${dependencies} CXX_STANDARD "${standard}" ${flags})
        endforeach()
        file(GLOB programs CONFIGURE_DEPENDS "${DESTINY_SOURCE_ROOT}/${path}/${category}/*.cpp")
        foreach(source IN LISTS programs)
            if(source IN_LIST assigned)
                continue()
            endif()
            get_filename_component(stem "${source}" NAME_WLE)
            _destiny_create_program("${path}" "${category}" "${stem}" SOURCES "${source}")
        endforeach()
    endforeach()
endfunction()
