include_guard(GLOBAL)

function(destiny_add_program category name)
    get_property(modules GLOBAL PROPERTY DESTINY_MODULES)
    if(NOT DEFINED _destiny_module_path OR NOT _destiny_module_path IN_LIST modules)
        message(FATAL_ERROR "Declare a module before its programs")
    endif()
    if(NOT category MATCHES "^(test|bench|demo)$" OR NOT name MATCHES "^[A-Za-z][A-Za-z0-9_-]*$")
        message(FATAL_ERROR "Use destiny_add_program(test|bench|demo name SOURCES ...)")
    endif()
    cmake_parse_arguments(P "CUSTOM_MAIN" "CXX_STANDARD" "SOURCES;DEPENDS" ${ARGN})
    if(P_UNPARSED_ARGUMENTS OR P_KEYWORDS_MISSING_VALUES OR NOT P_SOURCES)
        message(FATAL_ERROR "Invalid or incomplete program declaration: ${category}/${name}")
    endif()
    if(P_CUSTOM_MAIN AND NOT category STREQUAL "test")
        message(FATAL_ERROR "CUSTOM_MAIN applies only to test programs")
    endif()
    set(id "${category}/${name}")
    _destiny_get(programs "${_destiny_module_path}" PROGRAM_NAMES)
    if(id IN_LIST programs)
        message(FATAL_ERROR "Duplicate explicit program: ${_destiny_module_path}/${id}")
    endif()
    _destiny_get(standard "${_destiny_module_path}" CXX)
    if(DEFINED P_CXX_STANDARD)
        _destiny_max_standard(standard "${standard}" "${P_CXX_STANDARD}")
    endif()
    set(seen)
    foreach(source IN LISTS P_SOURCES)
        if(NOT source MATCHES "^${category}/.+\\.cpp$" OR source MATCHES "(^|/)\\.\\.?(/|$)|//|[\\\\;\n\r]")
            message(FATAL_ERROR "Program sources must be canonical paths below ${category}/: ${source}")
        endif()
        if(source IN_LIST seen)
            message(FATAL_ERROR "Duplicate source in ${id}: ${source}")
        endif()
        list(APPEND seen "${source}")
        set(absolute "${DESTINY_SOURCE_ROOT}/${_destiny_module_path}/${source}")
        if(NOT EXISTS "${absolute}" OR IS_DIRECTORY "${absolute}")
            message(FATAL_ERROR "Missing program source: ${absolute}")
        endif()
        file(REAL_PATH "${DESTINY_SOURCE_ROOT}/${_destiny_module_path}/${category}" source_root)
        file(REAL_PATH "${absolute}" resolved)
        cmake_path(IS_PREFIX source_root "${resolved}" NORMALIZE within)
        if(NOT within)
            message(FATAL_ERROR "Program source escapes its module: ${source}")
        endif()
    endforeach()
    list(APPEND programs "${id}")
    _destiny_set("${_destiny_module_path}" PROGRAM_NAMES "${programs}")
    foreach(field SOURCES DEPENDS CUSTOM_MAIN)
        _destiny_set("${_destiny_module_path}" "PROGRAM_${id}_${field}" "${P_${field}}")
    endforeach()
    _destiny_set("${_destiny_module_path}" "PROGRAM_${id}_CXX" "${standard}")
endfunction()

function(_destiny_resolve_programs)
    get_property(modules GLOBAL PROPERTY DESTINY_MODULES)
    get_property(layers GLOBAL PROPERTY DESTINY_LAYERS)
    foreach(module IN LISTS modules)
        string(REGEX REPLACE "/.*$" "" layer "${module}")
        list(FIND layers "${layer}" rank)
        _destiny_get(programs "${module}" PROGRAM_NAMES)
        foreach(id IN LISTS programs)
            _destiny_get(standard "${module}" "PROGRAM_${id}_CXX")
            _destiny_get(owner_standard "${module}" EFFECTIVE_CXX)
            _destiny_max_standard(standard "${standard}" "${owner_standard}")
            _destiny_get(dependencies "${module}" "PROGRAM_${id}_DEPENDS")
            foreach(dep IN LISTS dependencies)
                if(NOT dep IN_LIST modules)
                    message(FATAL_ERROR "Unknown program dependency ${dep}: ${module}/${id}")
                endif()
                string(REGEX REPLACE "/.*$" "" dep_layer "${dep}")
                list(FIND layers "${dep_layer}" dep_rank)
                if(NOT dep_rank LESS rank)
                    message(FATAL_ERROR "Program dependency must point to a strictly lower layer: ${module}/${id} -> ${dep}")
                endif()
                _destiny_get(required "${dep}" EFFECTIVE_PUBLIC_CXX)
                _destiny_max_standard(standard "${standard}" "${required}")
            endforeach()
            _destiny_set("${module}" "PROGRAM_${id}_EFFECTIVE_CXX" "${standard}")
        endforeach()
    endforeach()
endfunction()
