include_guard(GLOBAL)

function(_destiny_write_report)
    get_property(modules GLOBAL PROPERTY DESTINY_MODULES)
    set(report "Source selection report\ndestiny\n")
    set(data "{\"schema_version\":1,\"modules\":{},\"programs\":[]}")
    set(seen)
    foreach(path IN LISTS modules)
        string(REPLACE "/" ";" parts "${path}")
        set(prefix "")
        set(depth 0)
        foreach(part IN LISTS parts)
            math(EXPR depth "${depth} + 1")
            if(prefix)
                string(APPEND prefix "/${part}")
            else()
                set(prefix "${part}")
            endif()
            string(REPEAT "    " ${depth} indent)
            if(NOT prefix IN_LIST seen)
                string(APPEND report "${indent}${part}\n")
                list(APPEND seen "${prefix}")
            endif()
        endforeach()
        string(APPEND indent "    ")
        _destiny_get(standard "${path}" CXX)
        _destiny_get(effective "${path}" EFFECTIVE_CXX)
        _destiny_get(public "${path}" EFFECTIVE_PUBLIC_CXX)
        string(APPEND report "${indent}C++ minimum: ${standard}; effective: ${effective}; public: ${public}\n")
        _destiny_get(compilation "${path}" COMPILE_CONTEXT)
        string(JSON context_key GET "${compilation}" cache_key)
        string(APPEND report "${indent}Compilation context: ${context_key} (minimum mode verified; not full language conformance)\n")
        _destiny_get(selection "${path}" SELECTION)
        string(JSON records GET "${selection}" sources)
        string(JSON count LENGTH "${records}")
        if(count GREATER 0)
            math(EXPR last "${count} - 1")
            foreach(index RANGE 0 ${last})
                string(JSON source MEMBER "${records}" ${index})
                string(JSON selected GET "${records}" "${source}" selected)
                string(JSON reason GET "${records}" "${source}" reason)
                if(selected)
                    string(APPEND report "${indent}Selected: ${source} (${reason})\n")
                else()
                    string(APPEND report "${indent}Excluded: ${source} (${reason})\n")
                endif()
            endforeach()
        endif()
        string(JSON groups GET "${selection}" groups)
        string(JSON count LENGTH "${groups}")
        if(count GREATER 0)
            math(EXPR last "${count} - 1")
            foreach(index RANGE 0 ${last})
                string(JSON group MEMBER "${groups}" ${index})
                string(JSON winner GET "${groups}" "${group}")
                string(APPEND report "${indent}Implementation group ${group}: ${winner}\n")
            endforeach()
        endif()
        string(JSON selection SET "${selection}" declared_cxx_standard ${standard})
        string(JSON selection SET "${selection}" effective_cxx_standard ${effective})
        string(JSON selection SET "${selection}" effective_public_cxx_standard ${public})
        string(JSON selection SET "${selection}" compilation_context "${compilation}")
        string(JSON data SET "${data}" modules "${path}" "${selection}")
    endforeach()
    get_property(programs GLOBAL PROPERTY DESTINY_PROGRAMS)
    set(configure_report "${report}")
    set(index 0)
    foreach(entry IN LISTS programs)
        string(REPLACE "|" ";" entry "${entry}")
        list(GET entry 0 path)
        list(GET entry 1 category)
        list(GET entry 2 target)
        list(GET entry 3 stem)
        string(APPEND report "Executable [${path}/${category}]: $<TARGET_FILE:${target}>\nWorking directory: ${DESTINY_PROJECT_ROOT}\n")
        string(APPEND configure_report "Executable [${path}/${category}]: ${CMAKE_BINARY_DIR}/${path}/${category}/${stem}${CMAKE_EXECUTABLE_SUFFIX}\nWorking directory: ${DESTINY_PROJECT_ROOT}\n")
        set(program "{}")
        foreach(pair "module;${path}" "category;${category}" "target;${target}"
                     "executable;$<TARGET_FILE:${target}>" "working_directory;${DESTINY_PROJECT_ROOT}")
            list(GET pair 0 name)
            list(GET pair 1 value)
            _destiny_json_quote(value "${value}")
            string(JSON program SET "${program}" "${name}" "${value}")
        endforeach()
        string(JSON data SET "${data}" programs ${index} "${program}")
        math(EXPR index "${index} + 1")
    endforeach()
    file(GENERATE OUTPUT "${CMAKE_BINARY_DIR}/reports/source-selection-$<CONFIG>.txt" CONTENT "${report}")
    file(GENERATE OUTPUT "${CMAKE_BINARY_DIR}/reports/source-selection-$<CONFIG>.json" CONTENT "${data}\n")
    get_property(targets GLOBAL PROPERTY DESTINY_BUILD_TARGETS)
    add_custom_target(destiny_source_report
        COMMAND "${CMAKE_COMMAND}" -E cat "${CMAKE_BINARY_DIR}/reports/source-selection-$<CONFIG>.txt"
        VERBATIM)
    add_custom_target(destiny_build_summary ALL
        COMMAND "${CMAKE_COMMAND}" -E cat "${CMAKE_BINARY_DIR}/reports/source-selection-$<CONFIG>.txt"
        DEPENDS ${targets} VERBATIM)
    message(STATUS "${configure_report}")
endfunction()
