include_guard(GLOBAL)

function(_destiny_json_quote output value)
    string(REPLACE "\\" "\\\\" value "${value}")
    string(REPLACE "\"" "\\\"" value "${value}")
    string(REPLACE "\n" "\\n" value "${value}")
    string(REPLACE "\r" "\\r" value "${value}")
    string(REPLACE "\t" "\\t" value "${value}")
    set(${output} "\"${value}\"" PARENT_SCOPE)
endfunction()

function(_destiny_json_array output)
    set(result "[]")
    set(index 0)
    foreach(value IN LISTS ARGN)
        _destiny_json_quote(encoded "${value}")
        string(JSON result SET "${result}" ${index} "${encoded}")
        math(EXPR index "${index} + 1")
    endforeach()
    set(${output} "${result}" PARENT_SCOPE)
endfunction()

function(_destiny_write_if_changed path content)
    if(EXISTS "${path}")
        file(READ "${path}" previous)
        if(previous STREQUAL content)
            return()
        endif()
    endif()
    get_filename_component(parent "${path}" DIRECTORY)
    file(MAKE_DIRECTORY "${parent}")
    file(WRITE "${path}.tmp" "${content}")
    file(RENAME "${path}.tmp" "${path}")
endfunction()

function(_destiny_json_extract output document)
    string(JSON type TYPE "${document}" ${ARGN})
    string(JSON value GET "${document}" ${ARGN})
    if(type STREQUAL "BOOLEAN")
        if(value)
            set(value true)
        else()
            set(value false)
        endif()
    elseif(type STREQUAL "NULL")
        set(value null)
    elseif(type STREQUAL "STRING")
        _destiny_json_quote(value "${value}")
    endif()
    set(${output} "${value}" PARENT_SCOPE)
endfunction()
