include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/DestinyJson.cmake")

function(_destiny_members document required optional label)
    string(JSON type TYPE "${document}")
    if(NOT type STREQUAL "OBJECT")
        message(FATAL_ERROR "${label} must be an object")
    endif()
    string(JSON count LENGTH "${document}")
    set(found)
    if(count GREATER 0)
        math(EXPR last "${count} - 1")
        foreach(index RANGE 0 ${last})
            string(JSON name MEMBER "${document}" ${index})
            if(NOT name IN_LIST required AND NOT name IN_LIST optional)
                message(FATAL_ERROR "${label}: unknown member ${name}")
            endif()
            list(APPEND found "${name}")
        endforeach()
    endif()
    foreach(name IN LISTS required)
        if(NOT name IN_LIST found)
            message(FATAL_ERROR "${label}: missing member ${name}")
        endif()
    endforeach()
endfunction()

function(_destiny_expect_type document expected)
    string(JSON type TYPE "${document}" ${ARGN})
    if(NOT type STREQUAL expected)
        message(FATAL_ERROR "Expected ${expected} at ${ARGN}, received ${type}")
    endif()
endfunction()

function(_destiny_field output facts name)
    string(JSON value ERROR_VARIABLE error GET "${facts}" "${name}")
    if(error)
        message(FATAL_ERROR "Unknown condition field: ${name}")
    endif()
    set(${output} "${value}" PARENT_SCOPE)
endfunction()

function(_destiny_decimal value)
    if(NOT value MATCHES "^(0|-?[1-9][0-9]*)$")
        message(FATAL_ERROR "Integer comparison requires a canonical decimal string: ${value}")
    endif()
    string(REGEX REPLACE "^-" "" digits "${value}")
    string(LENGTH "${digits}" length)
    if(value MATCHES "^-")
        set(limit "9223372036854775808")
    else()
        set(limit "9223372036854775807")
    endif()
    if(length GREATER 19 OR (length EQUAL 19 AND digits STRGREATER limit))
        message(FATAL_ERROR "Integer comparison exceeds signed 64-bit range: ${value}")
    endif()
endfunction()

function(_destiny_integer_order output left right)
    _destiny_decimal("${left}")
    _destiny_decimal("${right}")
    if(left STREQUAL right)
        set(result 0)
    elseif(left MATCHES "^-" AND NOT right MATCHES "^-")
        set(result -1)
    elseif(right MATCHES "^-" AND NOT left MATCHES "^-")
        set(result 1)
    else()
        string(REGEX REPLACE "^-" "" a "${left}")
        string(REGEX REPLACE "^-" "" b "${right}")
        string(LENGTH "${a}" alen)
        string(LENGTH "${b}" blen)
        if(alen LESS blen OR (alen EQUAL blen AND a STRLESS b))
            set(result -1)
        else()
            set(result 1)
        endif()
        if(left MATCHES "^-")
            math(EXPR result "-${result}")
        endif()
    endif()
    set(${output} "${result}" PARENT_SCOPE)
endfunction()

function(_destiny_comparison output reason comparison facts)
    _destiny_members("${comparison}" "field;op;value" "unit" "Comparison")
    foreach(name field op value)
        _destiny_expect_type("${comparison}" STRING "${name}")
        string(JSON ${name} GET "${comparison}" "${name}")
    endforeach()
    _destiny_field(fact "${facts}" "${field}")
    string(JSON type GET "${fact}" type)
    string(JSON status GET "${fact}" status)
    string(JSON unit GET "${fact}" unit)
    string(JSON expected_unit ERROR_VARIABLE no_unit GET "${comparison}" unit)
    if(unit)
        if(no_unit OR NOT unit STREQUAL expected_unit)
            message(FATAL_ERROR "Comparison for ${field} requires unit ${unit}")
        endif()
    elseif(NOT no_unit)
        message(FATAL_ERROR "Comparison for ${field} does not accept a unit")
    endif()
    if(type STREQUAL "integer")
        if(NOT op MATCHES "^(eq|ne|lt|le|gt|ge)$")
            message(FATAL_ERROR "Invalid integer comparison operator: ${op}")
        endif()
        _destiny_decimal("${value}")
    elseif(type STREQUAL "string")
        if(NOT op MATCHES "^(eq|ne)$")
            message(FATAL_ERROR "String comparisons support eq and ne only")
        endif()
    else()
        message(FATAL_ERROR "Comparison field ${field} must be integer or string, received ${type}")
    endif()
    if(NOT status STREQUAL "available")
        string(JSON why GET "${fact}" reason)
        set(${output} FALSE PARENT_SCOPE)
        set(${reason} "${field}: ${status} (${why}); comparison is false" PARENT_SCOPE)
        return()
    endif()
    string(JSON actual GET "${fact}" value)
    if(type STREQUAL "integer")
        _destiny_integer_order(order "${actual}" "${value}")
    elseif(actual STREQUAL value)
        set(order 0)
    else()
        set(order 1)
    endif()
    set(result FALSE)
    if((op STREQUAL "eq" AND order EQUAL 0) OR
       (op STREQUAL "ne" AND NOT order EQUAL 0) OR
       (op STREQUAL "lt" AND order LESS 0) OR
       (op STREQUAL "le" AND order LESS_EQUAL 0) OR
       (op STREQUAL "gt" AND order GREATER 0) OR
       (op STREQUAL "ge" AND order GREATER_EQUAL 0))
        set(result TRUE)
    endif()
    set(${output} "${result}" PARENT_SCOPE)
    set(${reason} "${field} ${op} ${value}: ${result}" PARENT_SCOPE)
endfunction()

function(destiny_evaluate_condition output reason expression facts aliases)
    _destiny_evaluate(value explanation "${expression}" "${facts}" "${aliases}" "" 0)
    set(${output} "${value}" PARENT_SCOPE)
    set(${reason} "${explanation}" PARENT_SCOPE)
endfunction()

function(_destiny_evaluate output reason expression facts aliases stack depth)
    if(depth GREATER 64)
        message(FATAL_ERROR "Condition nesting exceeds 64 levels")
    endif()
    math(EXPR next_depth "${depth} + 1")
    string(JSON type TYPE "${expression}")
    if(type STREQUAL "BOOLEAN")
        string(JSON value GET "${expression}")
        set(${output} "${value}" PARENT_SCOPE)
        set(${reason} "Literal ${value}" PARENT_SCOPE)
        return()
    endif()
    _destiny_members("${expression}" "" "ref;all;any;not;compare" "Condition")
    string(JSON count LENGTH "${expression}")
    if(NOT count EQUAL 1)
        message(FATAL_ERROR "Condition must contain exactly one operator")
    endif()
    string(JSON operation MEMBER "${expression}" 0)
    _destiny_json_extract(operand "${expression}" "${operation}")
    if(operation STREQUAL "ref")
        string(JSON operand GET "${expression}" ref)
        _destiny_expect_type("${expression}" STRING ref)
        string(JSON alias ERROR_VARIABLE error GET "${aliases}" "${operand}")
        if(NOT error)
            _destiny_json_extract(alias "${aliases}" "${operand}")
            if(operand IN_LIST stack)
                message(FATAL_ERROR "Condition alias cycle: ${stack} -> ${operand}")
            endif()
            list(APPEND stack "${operand}")
            _destiny_evaluate(value why "${alias}" "${facts}" "${aliases}" "${stack}" ${next_depth})
        else()
            _destiny_field(fact "${facts}" "${operand}")
            string(JSON field_type GET "${fact}" type)
            if(NOT field_type STREQUAL "boolean")
                message(FATAL_ERROR "Condition reference ${operand} needs a boolean field or alias")
            endif()
            string(JSON status GET "${fact}" status)
            if(status STREQUAL "available")
                string(JSON value GET "${fact}" value)
                set(why "${operand} = ${value}")
            else()
                string(JSON detail GET "${fact}" reason)
                set(value FALSE)
                set(why "${operand}: ${status} (${detail}); effective false")
            endif()
        endif()
    elseif(operation STREQUAL "not")
        _destiny_evaluate(child why "${operand}" "${facts}" "${aliases}" "${stack}" ${next_depth})
        if(child)
            set(value FALSE)
        else()
            set(value TRUE)
        endif()
        set(why "NOT (${why}) = ${value}")
    elseif(operation STREQUAL "compare")
        _destiny_comparison(value why "${operand}" "${facts}")
    else()
        _destiny_expect_type("${operand}" ARRAY)
        string(JSON count LENGTH "${operand}")
        if(count EQUAL 0)
            message(FATAL_ERROR "${operation} needs at least one condition")
        endif()
        if(operation STREQUAL "all")
            set(value TRUE)
        else()
            set(value FALSE)
        endif()
        set(reasons)
        math(EXPR last "${count} - 1")
        foreach(index RANGE 0 ${last})
            _destiny_json_extract(child "${operand}" ${index})
            _destiny_evaluate(child_value child_reason "${child}" "${facts}" "${aliases}" "${stack}" ${next_depth})
            # Evaluate every branch so a true/false sibling cannot hide an invalid rule.
            if(operation STREQUAL "all" AND NOT child_value)
                set(value FALSE)
            elseif(operation STREQUAL "any" AND child_value)
                set(value TRUE)
            endif()
            list(APPEND reasons "${child_reason}")
        endforeach()
        string(JOIN ", " joined ${reasons})
        set(why "${operation} (${joined}) = ${value}")
    endif()
    set(${output} "${value}" PARENT_SCOPE)
    set(${reason} "${why}" PARENT_SCOPE)
endfunction()
